name: rental_maq
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  calendar_date_picker2: ^0.5.3
  currency_formatter: ^2.2.0
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  intl: ^0.18.0
  table_calendar: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
